export SHELL_HOME=~/dotfiles/shell
ZSH_THEME='rawsyntax'

source "$SHELL_HOME/alias"
source "$SHELL_HOME/env"
#source "$SHELL_HOME/zsh/light-weight.zsh"
source "$SHELL_HOME/zsh/oh-my.zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
