export ZSH_HOME="$HOME/dotfiles/zsh"
ZSH_THEME='minimal'
HISTFILE="$HOME/.zsh_history"
HISTSIZE=999999999
SAVEHIST=999999999
setopt BANG_HIST
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_VERIFY

autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:git:*' formats '%F{15}(%b)%f'
zstyle ':vcs_info:*' enable git
RPROMPT=\$vcs_info_msg_0_
PROMPT='%1~ %(?.#.!) '

source "$ZSH_HOME/alias"
source "$ZSH_HOME/env"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
